### ISSUE TITLE
bot brok

### ISSUE THREAD

**Issue by thomasgordon** [yakasov/bot-rewrite-3-js#158]
brooken

help

**Comment by thomasgordon** [comment]
thank you broken not thanking after Thank

**Comment by yakasov** [comment]
related code @ https://github.com/yakasov/bot-rewrite-3-js/blob/master/index.js?plain=1#L207-L261

**Comment by chtbaldwin2** [comment]
i am having this issue too it is brok

**Comment by chtbaldwin2** [comment]
please fix thx

**Comment by chtbaldwin2** [comment]
**### _

- [ ] - > `[aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa](url)`

_**
