### ISSUE TITLE
⚠️Bot Spam⚠️ 

### ISSUE THREAD

**Issue by minisplints** [yakasov/bot-rewrite-3-js#187]
![image](https://github.com/yakasov/bot-rewrite-3-js/assets/43448509/bb73c93b-9f21-4efc-b712-2043598afe45)

I'll use nerd emojis as a key.

🤓= 1 message

Human messages: 🤓🤓🤓

Bot messages: 🤓🤓🤓🤓🤓  🤓🤓🤓🤓🤓  🤓🤓🤓🤓🤓  🤓🤓

https://tenor.com/view/longestsoloever-lse-yapper-yapping-alert-gif-16222796328902842371

https://tenor.com/view/please-stop-nerd-please-stop-boiling-nerd-please-nerd-emoji-nerd-emoji-stop-boiling-pls-stop-nerd-gif-25254064

![image](https://github.com/yakasov/bot-rewrite-3-js/assets/43448509/b19f8b1c-cb9e-421d-8e7a-05a72a70c08c)

**Comment by yakasov** [comment]
changed channel
