### ISSUE TITLE
SUGGESTION - command to see the next birthday

### ISSUE THREAD

**Issue by thomasgordon** [yakasov/bot-rewrite-3-js#188]
title is self explanatory, a command that shows the next 1 or 3 birthdays on the server

**Comment by yakasov** [comment]
current date can be accessed with `globalThis.currentDate`
birthdays can be accessed using `const birthdays = require("../resources/birthdays.json");`

see date comparison @ https://github.com/yakasov/bot-rewrite-3-js/blob/4a22c7bcc53ceb9f08d77368b2ed598ea3a61f2e/tasks/birthdays.js#L11

**Comment by thomasgordon** [comment]
will get on it this evening, thanks for the info
